config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users
  resources :trails
  resources :pictures
  resources :videos
  resources :stories
  
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/privacy', to: 'static_pages#privacy'
  post 'static_pages/thank_you'


  root 'static_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :user
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    before_action :set_video, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!
    load_and_authorize_resource

    
    def index
        if params[:q]
            search_term = params[:q]
            @videos = Video.where("video_title || video_description ilike ?", "%#{search_term}%")
        else
            @videos = Video.all
        end
    end
    
    def show
    end
    
    def new
        @video = Video.new
    end
    
    def create
        @video = Video.new(video_params)
        
        respond_to do |format|
            if @video.save
                format.html { redirect_to @video, notice: 'The video was successfully created.' }
                format.json { render :show, status: :created, location: @video }
            else
                format.html { render :new }
                format.json { render json: @video.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def edit
    end
    
    def update
        respond_to do |format|
            if @video.update(video_params)
                format.html { redirect_to @video, notice: 'The video was successfully updated.' }
                format.json { render :show, status: :ok, location: @video }
            else
                format.html { render :edit }
                format.json { render json: @video.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def destroy
        @video.destroy
        respond_to do |format|
            format.html { redirect_to pictures_url, notice: "video was deleted." }
            format.json { head :no_content }
        end
    end
    
    private
        def set_video
            @video = Video.find(params[:id])
        end
        
        def video_params
            params.require(:video).permit(:user_id, :video_url, :video_title, :video_description)
        end
end

app/views/videos/_form.html.erb
<!--Video Add Form-->
<div class="container form">
    <div class="row">
        <div class="col-md-12">
            <%= form_for(video) do |f| %>
            <% if video.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>
                <ul>
                    <% video.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
            <% end %>
            <div class="field form-group">
                <%= f.label :video_title %>
                <%= f.text_field :video_title %>
            </div>
            <div class="field form-group">
                <%= f.label :video_url %>
                <%= f.text_field :video_url %>
            </div>
            <div class="field form-group">
                <%= f.label :video_description %>
                <%= f.text_field :video_description %>
            </div>
            <div class="actions form-group">
                <%= f.submit "Add", :class=>"btn btn-lg btn-primary" %>
            </div>
            <% end %>
        </div>
        <%= link_to 'Back', videos_path %>
    </div>
</div>

app/views/videos/index.html.erb
<div class="container main">
     <div class="row">
        <div class="col-md-12">
            <h1 class="text-center page-heading">Videos</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <%= link_to 'New Video', new_video_path, :class => "btn btn-primary" %>
        </div>
        <div class="col-md-6 col-xs-12">
            <%= form_tag("/videos", method: "get", :class => "pull-right") do %>
                <%= label_tag(:q, "Search for:") %>
                <%= text_field_tag(:q)%>
                <%= submit_tag("Search", :class => "btn btn-default") %>
             <% end %> 
        </div>
    </div>
     <div class="row text-center" style="display: flex; flex-wrap: wrap">
   <% @videos.each do |video| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="thumbnail">
          <h2><%= video.video_title %></h2>
            <video controls src="<%= video.video_url %>"></video>
            
            <%= link_to 'Show', video %>
           <%= link_to 'Edit', edit_video_path(video) %>
           <%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
      <% end %>
    </div>
   </div>
    
    <div class="container">

app/views/videos/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
             <h1 class="page-heading">Add a New Video</h1>   
        </div>
    </div>
</div>

<%= render 'form', video: @video %>


<div class="container">

app/views/videos/show.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-12">
        <h1 class="page-heading"><%= @video.video_title %></h1>
      </div>
  </div>
   <div class="row text-center">
      <div class="col-md-12 player-section">
          <div class="thumbnail" id="videoplayer">
            <video controls src="<%= @video.video_url%>" height="500"></video>
            <p><%= @video.video_description%></p>
          </div>
        </div>
   </div>
</div> <!-- Close main container --> 
<div class="container footer">