config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users
  resources :trails
  resources :pictures
  resources :videos
  resources :stories
  
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/privacy', to: 'static_pages#privacy'
  post 'static_pages/thank_you'


  root 'static_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
 <!--Footer code-->
        <footer class="row">
    <div class="col-sm-4 col-xs-4">
        <h4>Media</h4>
        <p><a href="<%= pictures_path%>">Images</a></p>
        <p><a href="<%= videos_path%>">Videos</a></p>
        <p><a href="<%= stories_path%>">Stories</a></p>

    </div>
    <div class="col-sm-4 col-xs-4">
        <h4>My Account</h4>
        <p><a href="#">Login</a></p>
        <p><a href="#">Register</a></p>
        <p><a href="#">My Profile</a></p>

    </div>
    <div class="col-sm-4 col-xs-4">
        <h4>About Us</h4>
        <p><a href="<%= about_path%>">What We Do</a></p>
        <p><a href="<%= contact_path %>">Contact Us</a></p>
        <p><a href="<%= privacy_path%>">Privacy Policy</a></p>

    </div>
</footer>

app/views/shared/_header.html.erb
<!--Header content-->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <img id="logo-icon" src="http://imgh.us/compass_2.svg">
            <a class="navbar-brand" href="/">HikingWorld</a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mynavbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="mynavbar">
            <ul class="nav navbar-nav navbar-right">
                <li id="notice"><%= notice %></li>
                <li><a href="<%= trails_path %>">Trails</a></li>
                <li><a href="<%= pictures_path%>">Images</a></li>
                <li><a href="<%= videos_path%>">Videos </a></li>
                <li><a href="<%= stories_path%>">Stories</a></li>
                    <% if user_signed_in? %>
                        <li><%= link_to("Manage Account", edit_user_registration_path)%></li>
                        <li><%= link_to("Logout", destroy_user_session_path, :method => :delete) %></li>
                    <% else %>
                        <li><%= link_to("Register", new_user_registration_path) %></li>
                        <li><%= link_to("Login", new_user_session_path) %></li>
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
</nav>