config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users
  resources :trails
  resources :pictures
  resources :videos
  resources :stories
  
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/privacy', to: 'static_pages#privacy'
  post 'static_pages/thank_you'


  root 'static_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trail.rb
class Trail < ApplicationRecord
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  before_action :set_trail, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:edit, :update, :create, :new, :destroy]
  load_and_authorize_resource

  # GET /trails
  # GET /trails.json
  def index
    if params[:q]
      # Return filtered list
      search_term = params[:q]
      @trails = Trail.where("name || location ilike ?", "%#{search_term}%")
    else
      @trails = Trail.all
    end
  end

  # GET /trails/1
  # GET /trails/1.json
  def show
  end

  # GET /trails/new
  def new
    @trail = Trail.new
  end

  # GET /trails/1/edit
  def edit
  end

  # POST /trails
  # POST /trails.json
  def create
    @trail = Trail.new(trail_params)

    respond_to do |format|
      if @trail.save
        format.html { redirect_to @trail, notice: 'Trail was successfully created.' }
        format.json { render :show, status: :created, location: @trail }
      else
        format.html { render :new }
        format.json { render json: @trail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trails/1
  # PATCH/PUT /trails/1.json
  def update
    respond_to do |format|
      if @trail.update(trail_params)
        format.html { redirect_to @trail, notice: 'Trail was successfully updated.' }
        format.json { render :show, status: :ok, location: @trail }
      else
        format.html { render :edit }
        format.json { render json: @trail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trails/1
  # DELETE /trails/1.json
  def destroy
    @trail.destroy
    respond_to do |format|
      format.html { redirect_to trails_url, notice: 'Trail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trail
      @trail = Trail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trail_params
      params.require(:trail).permit(:name, :image, :description, :location, :features, :rating, :difficulty, :latitude, :longitude)
    end
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/views/trails/_form.html.erb
<div class="container form">
    <div class="row">
        <div class="col-md-12">
          <%= form_for(trail) do |f| %>
<% if trail.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(trail.errors.count, "error") %> prohibited this trail from being saved:</h2>
    <ul>
        <% trail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>
            <div class="field form-group">
                <%= f.label :name %>
                <%= f.text_field :name %>
            </div>
            <div class="field form-group">
                <%= f.label :image %>
                <%= f.text_field :image %>
            </div>
            <div class="field form-group">
                <%= f.label :description %><br>
                <%= f.text_area :description %>
            </div>
            <div class="field form-group">
                <%= f.label :location, "City and State" %>
                <%= f.text_field :location %>
            </div>
            <div class="field form-group">
              <%= f.label :latitude %>
              <%= f.text_field :latitude%>
            </div>
            <div class="field form-group">
              <%= f.label :longitude %>
              <%= f.text_field :longitude%>
            </div>
            <div class="field form-group">
                <%= f.label :features %><br>
                <%= f.text_area :features %>
            </div>
            <div class="field form-group">
              <%= f.label :rating, "Rating: From 1-5" %> <br>
              <%= f.text_field :rating %>
            </div>
            <div class="field form-group">
              <%= f.label :difficulty, "Difficulty (easy, medium, hard)"%><br>
              <%= f.text_field :difficulty %>
            </div>
            <div class="actions form-group">
                <%= f.submit "Add", :class=>"btn btn-lg btn-primary" %>
            </div>
            <% end %>
        </div>
        <%= link_to 'Back', trails_path %>
    </div>
</div>

app/views/trails/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
             <h1 class="page-heading">Edit Trail Info</h1>   
        </div>
    </div>
</div>
<%= render 'form', trail: @trail %>

<%= link_to 'Show', @trail %> |
<%= link_to 'Back', trails_path %>

<div class="container">

app/views/trails/index.html.erb
<div class="container main">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center page-heading">Trails</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <%= link_to 'New Trail', new_trail_path, :class => "btn btn-primary" %>
        </div>
        <div class="col-md-6 col-xs-12">
            <%= form_tag("/trails", method: "get", :class => "pull-right") do %>
                <%= label_tag(:q, "Search for:") %>
                <%= text_field_tag(:q)%>
                <%= submit_tag("Search", :class => "btn btn-default") %>
             <% end %> 
        </div>
    </div>
     
<div class="row text-center" style="display: flex; flex-wrap: wrap">
   <% @trails.each do |trail| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="thumbnail">
          <h2><%= trail.name %></h2>
          <h3>Difficulty: <%= trail.difficulty%></h3>
          <h3><%= trail.rating %> Stars</h3>
            <img class="img-responsive" src="<%= trail.image %>">
            <div class="caption">
                <h4><%= trail.location%></h4>
            </div>
            
           <%= link_to 'Show', trail %>
           <%= link_to 'Edit', edit_trail_path(trail) %>
           <%= link_to 'Destroy', trail, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
      <% end %>
    </div>
   </div>
    
    <div class="container">

app/views/trails/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
             <h1 class="page-heading">Add a New Trail</h1>   
        </div>
    </div>
</div>

<%= render 'form', trail: @trail %>


<div class="container">

app/views/trails/show.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-12">
        <h1 class="page-heading"><%= @trail.name %></h1>
        <h3 class="text-center">Location: <%= @trail.location%></h3>
        <h3 class="text-center">Difficulty: <%= @trail.difficulty%></h3>
        <h3 class="text-center">Rating: <%= @trail.rating %></h3>
      </div>
  </div>
   <div class="row text-center">
      <div class="col-md-12">
          <div class="thumbnail" id="imagebox">
            <%= image_tag(@trail.image, class: "img-responsive")%>
          </div>
        </div>
   </div>
   
   <div class="row">
     <div class="col-md-12">
           <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#description" role="tab">Description</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#features" role="tab">Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#map" role="tab">Map</a>
            </li>
        </ul>
    
    <!--Info boxes-->
    <div class="tab-content">
            <div class="tab-pane active" id="description" role="tabpanel">
                <div id="description">
                    <div class="row">
                      <div class="col-md-4">
                        <p><%= @trail.description %></p>
                      </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="features" role="tabpanel">
                <div id="features">
                    <div class="row">
                      <div class="col-md-4">
                          <p><%= @trail.features %></p>
                      </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="map" role="tabpanel">
                <div id="map">
                    <div class="row">
                      <div class="col-md-12">
                          <iframe id="map" width="70%" height="400" frameborder="0" style="border:0"
 src="https://www.google.com/maps/embed/v1/view?key=AIzaSyDwssI058aGR1CHqFW3VMYG8InET6lxh5A&center=<%= @trail.latitude%>,<%=@trail.longitude%>&zoom=18%mapType=satellite"
 allowfullscreen></iframe>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   </div>
</div> <!-- Close main container --> 
<div class="container footer">