config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users
  resources :trails
  resources :pictures
  resources :videos
  resources :stories
  
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/privacy', to: 'static_pages#privacy'
  post 'static_pages/thank_you'


  root 'static_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :user
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    before_action :set_picture, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!
    load_and_authorize_resource
    
    def index
        if params[:q]
            search_term = params[:q]
            @pictures = Picture.where("caption ilike ?", "%#{search_term}%")
        else
            @pictures = Picture.all
        end
    end
    
    def show
    end
    
    def new
        @picture = Picture.new
    end
    
    def create
        @picture = Picture.new(picture_params)
        
        respond_to do |format|
            if @picture.save
                format.html { redirect_to @picture, notice: 'The picture was successfully created.' }
                format.json { render :show, status: :created, location: @picture }
            else
                format.html { render :new }
                format.json { render json: @picture.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def edit
    end
    
    def update
        respond_to do |format|
            if @picture.update(picture_params)
                format.html { redirect_to @picture, notice: 'The picture was successfully updated.' }
                format.json { render :show, status: :ok, location: @picture }
            else
                format.html { render :edit }
                format.json { render json: @picture.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def destroy
        @picture.destroy
        respond_to do |format|
            format.html { redirect_to pictures_url, notice: "Picture was deleted." }
            format.json { head :no_content }
        end
    end
    
    private
        def set_picture
            @picture = Picture.find(params[:id])
        end
        
        def picture_params
            params.require(:picture).permit(:user_id, :image_url, :caption)
        end
end

app/views/pictures/_form.html.erb
<!--Picture Add Form-->
<div class="container form">
    <div class="row">
        <div class="col-md-12">
            <%= form_for(picture) do |f| %>
            <% if picture.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>
                <ul>
                    <% picture.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
            <% end %>
            <div class="field form-group">
                <%= f.label :caption %>
                <%= f.text_field :caption %>
            </div>
            <div class="field form-group">
                <%= f.label :image_url %>
                <%= f.text_field :image_url %>
            </div>
            <div class="actions form-group">
                <%= f.submit "Add", :class=>"btn btn-lg btn-primary" %>
            </div>
            <% end %>
        </div>
        <%= link_to 'Back', pictures_path %>
    </div>
</div>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container main">
     <div class="row">
        <div class="col-md-12">
            <h1 class="text-center page-heading">Pictures</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-xs-12">
            <%= link_to 'New Picture', new_picture_path, :class => "btn btn-primary" %>
        </div>
        <div class="col-md-6 col-xs-12">
            <%= form_tag("/pictures", method: "get", :class => "pull-right") do %>
                <%= label_tag(:q, "Search for:") %>
                <%= text_field_tag(:q)%>
                <%= submit_tag("Search", :class => "btn btn-default") %>
             <% end %> 
        </div>
    </div>
     <div class="row text-center" style="display: flex; flex-wrap: wrap">
   <% @pictures.each do |picture| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="thumbnail">
          <h2><%= picture.caption %></h2>
            <img class="img-responsive" src="<%= picture.image_url %>">
            
            <%= link_to 'Show', picture %>
           <%= link_to 'Edit', edit_picture_path(picture) %>
           <%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
      <% end %>
    </div>
   </div>
    
    <div class="container">

app/views/pictures/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
             <h1 class="page-heading">Add a New Picture</h1>   
        </div>
    </div>
</div>

<%= render 'form', picture: @picture %>


<div class="container">

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
      <div class="col-md-12">
        <h1 class="page-heading"><%= @picture.caption %></h1>
      </div>
  </div>
   <div class="row text-center">
      <div class="col-md-12">
          <div class="thumbnail" id="imagebox">
            <%= image_tag(@picture.image_url, class: "img-responsive")%>
          </div>
        </div>
   </div>
</div> <!-- Close main container --> 
<div class="container footer">